package it.polimi.ingsw.Events;

public enum Events_Enum {
    TEST1, TEST2,
    DISCARD_TWO_BLUE, DISCARD_TWO_GREEN, DISCARD_TWO_YELLOW, DISCARD_TWO_PURPLE,
    PLUS_TWO_FAITH, PLUS_ONE_FAITH, SHUFFLE_ACTION,
    VATICAN_REPORT_1, VATICAN_REPORT_2, VATICAN_REPORT_3,
    LAST_ROUND
}
